import { Ubuntu_Sans } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import { AuthProvider } from "@/lib/auth/AuthContext"
import { ThemeProvider } from "@/components/theme-provider.jsx"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const ubuntuSans = localFont({
  src: [
    { path: "./fonts/UbuntuSans-VariableFont.ttf", style: "normal" },
    { path: "./fonts/UbuntuSans-Italic.ttf", style: "italic" },
  ],
  variable: "--font-ubuntu-sans",
  display: "swap",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntuSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
