import localFont from "next/font/local"
import "./globals.css"
import { AuthProvider } from "@/lib/auth/AuthContext"
import { ThemeProvider } from "@/components/theme-provider.jsx"
import { Patrick_Hand } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const patrick = Patrick_Hand({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-patrick",
})
const ubuntuSans = localFont({
  src: [
    { path: "./fonts/UbuntuSans-VariableFont.ttf", style: "normal" },
    { path: "./fonts/UbuntuSans-Italic.ttf", style: "italic" },
  ],
  variable: "--font-ubuntu-sans",
  display: "swap",
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${patrick.variable} ${ubuntuSans.variable}`}
      suppressHydrationWarning
    >
      <body className={`antialiased`} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          themes={["light", "dark", "sketch"]}
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
